=== Sbord1/eldoubleubet/codice/fileXML/scommesseUtenti/scommesseTennis.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Definisco le scommesse relative al tennis di un utente -->
<!ELEMENT scommesseTennis (scommessa*)>
<!ELEMENT scommessa (idPartita, idScommessa, scommettitore, risultato, puntata, quota, vincita)>

<!ATTLIST scommessa
              eliminato (1 | 0) "0"
              pagata (1 | 0) "0"> 

<!ELEMENT idPartita (#PCDATA)>

<!ELEMENT idScommessa (#PCDATA)>

<!ELEMENT scommettitore (#PCDATA)>

<!ELEMENT risultato (#PCDATA)>

<!ELEMENT puntata (#PCDATA)>

<!ELEMENT quota (#PCDATA)>

<!ELEMENT vincita (#PCDATA)>

=== Sbord1/eldoubleubet/codice/fileXML/scommesseUtenti/scommesseTennis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scommesseTennis SYSTEM "scommesseTennis.dtd">
<!-- Esempi di 3 scommesse di tennis -->
<scommesseTennis>
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>mario</scommettitore>
        <risultato>1</risultato>
        <puntata>30</puntata>
    </scommessa>
    
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>mario</scommettitore>
        <risultato>2</risultato>
        <puntata>18</puntata>
    </scommessa>
   
    <scommessa eliminato="0">
        <id>2</id>
        <scommettitore>ciruzzo</scommettitore>
        <risultato>1</risultato>
        <puntata>10</puntata>
    </scommessa>
</scommesseTennis>
