=== Sbord1/eldoubleubet/codice/fileXML/scommesseUtenti/scommesseIppica.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT scommesseIppica (scommessa*)>

<!ELEMENT scommessa (idPartita, idScommessa, scommettitore, risultato, puntata, quota, vincita)>

<!ATTLIST scommessa
            eliminato (0 | 1) "0"
            pagata (0 | 1) "0">

<!ELEMENT idPartita (#PCDATA)>

<!ELEMENT idScommessa (#PCDATA)>

<!ELEMENT scommettitore (#PCDATA)>

<!ELEMENT risultato (primo, secondo, terzo)>

<!ELEMENT primo (#PCDATA)>

<!ELEMENT secondo (#PCDATA)>

<!ELEMENT terzo (#PCDATA)>

<!ELEMENT puntata (#PCDATA)>

<!ELEMENT quota (#PCDATA)>

<!ELEMENT vincita (#PCDATA)>

=== Sbord1/eldoubleubet/scommesseIppica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scommesseIppica SYSTEM "scommesseIppica.dtd">

<!-- Abbiamo 2 scommesse, fatte da 2 utenti diversi, ma che fanno entrambe riferimento alla stessa scommessa avente id=1 nel file ippica.xml -->

<scommesseIppica>

    <!-- "eliminato" indica se la scommessa e' stata eliminata dal gestore (0 se non eliminata, altrimenti 1)-->
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>matteo</scommettitore>
        <risultato>
            <primo>5</primo>
            <secondo>2</secondo>
            <terzo>1</terzo>
        </risultato>
        <puntata>5</puntata>
    </scommessa>

    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>andrea</scommettitore>
        <risultato>
            <primo>1</primo>
            <secondo>3</secondo>
            <terzo>6</terzo>
        </risultato>
        <puntata>10</puntata>
    </scommessa>

</scommesseIppica>

=== Sbord1/eldoubleubet/codice/fileXML/scommesseUtenti/scommesseIppica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scommesseIppica SYSTEM "scommesseIppica.dtd">
<!-- Abbiamo 2 scommesse, fatte da 2 utenti diversi, ma che fanno entrambe riferimento alla stessa scommessa avente id=1 nel file ippica.xml -->
<scommesseIppica>

    <!-- "eliminato" indica se la scommessa e' stata eliminata dal gestore (0 se non eliminata, altrimenti 1)-->
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>matteo</scommettitore>
        <risultato>
            <primo>5</primo>
            <secondo/>
            <terzo/>
        </risultato>
        <puntata>5</puntata>
    </scommessa>

    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>andrea</scommettitore>
        <risultato>
            <primo/>
            <secondo>3</secondo>
            <terzo/>
        </risultato>
        <puntata>10</puntata>
    </scommessa>


</scommesseIppica>
