=== Sbord1/eldoubleubet/codice/fileXML/proposte/proposteScommessaTennis.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Definisco le scommesse relative al tennis -->
<!ELEMENT proposteScommessaTennis (propostaScommessa*)>
<!ELEMENT propostaScommessa (id, nome, quotaTennis, ora, data, puntata, utente)>

<!ELEMENT id (#PCDATA)>

<!ELEMENT nome (giocatoreCasa, giocatoreTrasferta)>
<!ELEMENT giocatoreCasa (#PCDATA)>
<!ELEMENT giocatoreTrasferta (#PCDATA)>

<!-- quotaTennis è composta da: vittoria casa (1), vittoria trasferta (2) -->

<!ELEMENT quotaTennis (quota1, quota2)> 
<!ELEMENT quota1 (#PCDATA)>
<!ELEMENT quota2 (#PCDATA)>

<!ELEMENT ora (oraInizio, oraFine)>
<!ELEMENT oraInizio (#PCDATA)>
<!ELEMENT oraFine (#PCDATA)>

<!ELEMENT data (giorno, mese, anno)>
<!ELEMENT giorno (#PCDATA)>
<!ELEMENT mese (#PCDATA)>
<!ELEMENT anno (#PCDATA)>

<!-- puntata è composta da un valore minimo e un valore massimo di puntata -->
<!ELEMENT puntata (minima, massima)>
<!ELEMENT minima (#PCDATA)>
<!ELEMENT massima (#PCDATA)>

<!ELEMENT utente (#PCDATA)>

=== Sbord1/eldoubleubet/proposteScommessaTennis.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proposteScommessaTennis SYSTEM "proposteScommessaTennis.dtd">
<!-- Esempio di 1 proposta di partita di tennis dall'utente mario -->

<proposteScommessaTennis>
 <proposteScommessa>
  	<id> 10 </id>
	<nome>
		<giocatoreCasa> Fritz T. </giocatoreCasa>
		<giocatoreTrasferta> Paul T. </giocatoreTrasferta>
	</nome>
	<quotaTennis>
      		<quota1> 1.35 </quota1>
      		<quota2> 1.99 </quota2>
  </quotaTennis>
  <ora>
        	<oraInizio> 15:00 </oraInizio>
        	<oraFine> 17:00 </oraFine>
	</ora>
	<data>
    		<giorno> 10 </giorno>
    		<mese> 01 </mese>
    		<anno> 2020 </anno>
  </data>
	<puntata>
		    <minima> 1 </minima>
		    <massima> 9999 </massima>
	</puntata>
	<utente> mario </utente>
</proposteScommessa>
</proposteScommessaTennis>
