=== Sbord1/eldoubleubet/basket.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Definisco le scommesse relative al basket -->
<!ELEMENT basket (id, nome, quotaBasket, ora, data, puntata)>

<!ELEMENT id (#PCDATA)>

<!ELEMENT nome (squadraCasa, squadraTrasferta)>
<!ELEMENT squadraCasa (#PCDATA)>
<!ELEMENT squadraTrasferta (#PCDATA)>

<!-- quotaBasket è composta da: vittoria casa (1), vittoria trasferta (2) -->

<!ELEMENT quotaBasket (quota1, quota2> 
<!ELEMENT quota1 (#PCDATA)>
<!ELEMENT quota2 (#PCDATA)>

<!ELEMENT ora (oraInizio, oraFine)>
<!ELEMENT oraInizio (#PCDATA)>
<!ELEMENT oraFine (#PCDATA)>

<!ELEMENT data (giorno, mese, anno)>
<!ELEMENT giorno (#PCDATA)>
<!ELEMENT mese (#PCDATA)>
<!ELEMENT anno (#PCDATA)>

<!-- puntata è composta da un valore minimo e un valore massimo di puntata -->
<!ELEMENT puntata (minima, massima)>
<!ELEMENT minima (#PCDATA)>
<!ELEMENT massima (#PCDATA)>

=== Sbord1/eldoubleubet/basket.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM "basket.dtd">
<!-- Esempi di 3 partite di basket -->
<basket>
	<id> 1 </id>
	<nome>
		<squadraCasa> Boston Celtics </squadraCasa>
		<squadraTrasferta> Milwaukee Bucks </squadraTrasferta>
	</nome>
	<quotaBasket>
      		<quota1> 2.35 </quota1>
      		<quota2> 1.49 </quota2>
    	</quotaBasket>
    	<ora> 
          	<oraInizio> 22:00 </oraInizio>
          	<oraFine> 23:30 </oraFine>
   	</ora>
    	<data>
      		<giorno> 22 </giorno>
      		<mese> 07 </mese>
      		<anno> 2021 <anno>
    	</data>
	<puntata>
		<minima> 1 </minima>
		<massima> 9999 <massima>
	</puntata>
	
  	<id> 2 </id>
	<nome>
		<squadraCasa> Philadelphia 76ers </squadraCasa>
		<squadraTrasferta> Brooklyn Nets </squadraTrasferta>
	</nome>
	<quotaBasket>
      		<quota1> 1.75 </quota1>
      		<quota2> 1.89 </quota2>
    	</quotaBasket>
    	<ora> 
          	<oraInizio> 22:00 </oraInizio>
          	<oraFine> 23:30 </oraFine>
	</ora>
	<data>
          	<giorno> 25 </giorno>
          	<mese> 09 </mese>
          	<anno> 2011 <anno>
	</data>
	<puntata>
		<minima> 1 </minima>
		<massima> 9999 <massima>
	</puntata>
	
  	<id> 3 </id>
	<nome>
		<squadraCasa> Toronto Raptors </squadraCasa>
		<squadraTrasferta> Chicago Bulls </squadraTrasferta>
	</nome>
	<quotaBasket>
      		<quota1> 1.90 </quota1>
      		<quota2> 1.85 </quota2>
    	</quotaBasket>
    	<ora> 
          	<oraInizio> 22:00 </oraInizio>
          	<oraFine> 23:30 </oraFine>
    	</ora>
    	<data>
          	<giorno> 15 </giorno>
          	<mese> 03 </mese>
          	<anno> 2023 <anno>
    	</data>
	<puntata>
		<minima> 1 </minima>
		<massima> 9999 <massima>
	</puntata>
</basket>
