=== Sbord1/eldoubleubet/calcio.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Definisco le scommesse relative al calcio -->
<!ELEMENT calcio (id, nome, quotaCalcio, ora, data, puntata>

<!ELEMENT id (#PCDATA)>

<!ELEMENT nome (squadraCasa, squadraTrasferta)>
<!ELEMENT squadraCasa (#PCDATA)>
<!ELEMENT squadraTrasferta (#PCDATA)>

<!-- quotaCalcio è composta da: vittoria casa (1), pareggio (x), vittoria trasferta (2),
quotaUnder si riferisce ad Under 2.5 goal è vinta quando in totale le squadre segnano al più 2 goal analogamente per Over
quotaGG è vinta quando entrambe le squadre segnano, analogamente per quotaNG è vinta quanto senza al più una squadra -->

<!ELEMENT quotaCalcio (quota1, quotax, quota2, quotaUnder, quotaOver, quotaGG, quotaNG> 
<!ELEMENT quota1 (#PCDATA)>
<!ELEMENT quotax (#PCDATA)>
<!ELEMENT quota2 (#PCDATA)>
<!ELEMENT quotaUnder (#PCDATA)>
<!ELEMENT quotaOver (#PCDATA)>
<!ELEMENT quotaGG (#PCDATA)>
<!ELEMENT quotaNG (#PCDATA)>

<!ELEMENT ora (oraInizio, oraFine)>
<!ELEMENT oraInizio (#PCDATA)>
<!ELEMENT oraFine (#PCDATA)>

<!ELEMENT data (giorno, mese, anno)>
<!ELEMENT giorno (#PCDATA)>
<!ELEMENT mese (#PCDATA)>
<!ELEMENT anno (#PCDATA)>

<!-- puntata è composta da un valore minimo e un valore massimo di puntata -->
<!ELEMENT puntata (minima, massima)>
<!ELEMENT minima (#PCDATA)>
<!ELEMENT massima (#PCDATA)>

=== Sbord1/eldoubleubet/calcio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calcio SYSTEM "calcio.dtd">
<!-- Esempi di 3 partite di calcio -->

<calcio>
	<scommessa>
		<id> 1 </id>
		<nome>
			<squadraCasa> Milan </squadraCasa>
			<squadraTrasferta> Inter </squadraTrasferta>
		</nome>
		<quotaCalcio>
      			<quota1> 2.12 </quota1>
      			<quotax> 3.55 </quotax>
      			<quota2> 1.89 </quota2>
			<quotaUnder> 1.88 </quotaUnder>
			<quotaOver> 1.74 </quotaOver>
			<quotaGG> 1.55 </quotaGG>
			<quotaNG> 1.85 </quotaNG>
     		 </quotaCalcio>
    		<ora>
			<oraInizio> 20:45 </oraInizio>
			<oraFine> 22:15 </oraFine>
		</ora>
		<data>
			<giorno> 20 </giorno>
			<mese> 03 </mese>
			<anno> 2018 </anno>
		</data>
		<puntata>
			<minima> 1 </minima>
			<massima> 9999 </massima>
		</puntata>
	</scommessa>
	<scommessa>
  		<id> 2 </id>
		<nome>
			<squadraCasa> Roma </squadraCasa>
			<squadraTrasferta> Lazio </squadraTrasferta>
		</nome>
		<quotaCalcio>
      			<quota1> 1.45 </quota1>
      			<quotax> 3.12 </quotax>
      			<quota2> 2.34 </quota2>
			<quotaUnder> 1.48 </quotaUnder>
			<quotaOver> 1.94 </quotaOver>
			<quotaGG> 1.25 </quotaGG>
			<quotaNG> 1.85 </quotaNG>
      		</quotaCalcio>
    		<ora> 
			<oraInizio> 20:45 </oraInizio>
			<oraFine> 22:15 </oraFine>
		</ora>
		<data>
			<giorno> 25 </giorno>
			<mese> 05 </mese>
			<anno> 2022 </anno>
		</data>
		<puntata>
			<minima> 1 </minima>
			<massima> 9999 </massima>
		</puntata>
	</scommessa>
	<scommessa>
  		<id> 3 </id>
		<nome>
			<squadraCasa> Juventus </squadraCasa>
			<squadraTrasferta> Torino </squadraTrasferta>
		</nome>
		<quotaCalcio>
     			<quota1> 1.35 </quota1>
      			<quotax> 3.89 </quotax>
      			<quota2> 2.89 </quota2>
			<quotaUnder> 1.88 </quotaUnder>
			<quotaOver> 1.34 </quotaOver>
			<quotaGG> 1.95 </quotaGG>
			<quotaNG> 1.25 </quotaNG>
      		</quotaCalcio>
    		<ora>
			<oraInizio> 20:45 </oraInizio>
			<oraFine> 22:15 </oraFine>
		</ora>
		<data>
			<giorno> 25 </giorno>
			<mese> 05 </mese>
			<anno> 2022 </anno>
		</data>
		 <puntata>
			<minima> 1 </minima>
			<massima> 9999 </massima>
		</puntata>
	</scommessa>
</calcio>

=== Sbord1/eldoubleubet/codice/fileXML/scommesseDisponibili/calcio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calcio SYSTEM "calcio.dtd">
<!-- Esempi di 3 partite di calcio -->
<calcio>
  <scommessa eliminato="0">
    <id> 1 </id>
    <nome>
      <squadraCasa> Milan </squadraCasa>
      <squadraTrasferta> Inter </squadraTrasferta>
    </nome>
    <quotaCalcio>
      <quota1> 2.12 </quota1>
      <quotax> 3.55 </quotax>
      <quota2> 1.89 </quota2>
      <quotaUnder> 1.88 </quotaUnder>
      <quotaOver> 1.74 </quotaOver>
      <quotaGG> 1.55 </quotaGG>
      <quotaNG> 1.85 </quotaNG>
    </quotaCalcio>
    <ora>
      <oraInizio> 20:45 </oraInizio>
      <oraFine> 22:15 </oraFine>
    </ora>
    <data>
      <giorno> 20 </giorno>
      <mese> 03 </mese>
      <anno> 2018 </anno>
    </data>
    <puntata>
      <minima> 1 </minima>
      <massima> 9999 </massima>
    </puntata>
    <risultato>
      <puntiSquadraCasa>3</puntiSquadraCasa>
      <puntiSquadraTrasferta>1</puntiSquadraTrasferta>
    </risultato>
  </scommessa>
  <scommessa eliminato="0">
    <id> 2 </id>
    <nome>
      <squadraCasa> Roma </squadraCasa>
      <squadraTrasferta> Lazio </squadraTrasferta>
    </nome>
    <quotaCalcio>
      <quota1> 1.45 </quota1>
      <quotax> 3.12 </quotax>
      <quota2> 2.34 </quota2>
      <quotaUnder> 1.48 </quotaUnder>
      <quotaOver> 1.94 </quotaOver>
      <quotaGG> 1.25 </quotaGG>
      <quotaNG> 1.85 </quotaNG>
    </quotaCalcio>
    <ora>
      <oraInizio> 20:45 </oraInizio>
      <oraFine> 22:15 </oraFine>
    </ora>
    <data>
      <giorno> 25 </giorno>
      <mese> 05 </mese>
      <anno> 2022 </anno>
    </data>
    <puntata>
      <minima> 1 </minima>
      <massima> 9999 </massima>
    </puntata>
    <risultato>
      <puntiSquadraCasa>1</puntiSquadraCasa>
      <puntiSquadraTrasferta>2</puntiSquadraTrasferta>
    </risultato>
  </scommessa>
  <scommessa eliminato="0">
    <id> 3 </id>
    <nome>
      <squadraCasa> Juventus </squadraCasa>
      <squadraTrasferta> Torino </squadraTrasferta>
    </nome>
    <quotaCalcio>
      <quota1> 1.35 </quota1>
      <quotax> 3.89 </quotax>
      <quota2> 2.89 </quota2>
      <quotaUnder> 1.88 </quotaUnder>
      <quotaOver> 1.34 </quotaOver>
      <quotaGG> 1.95 </quotaGG>
      <quotaNG> 1.25 </quotaNG>
    </quotaCalcio>
    <ora>
      <oraInizio> 20:45 </oraInizio>
      <oraFine> 22:15 </oraFine>
    </ora>
    <data>
      <giorno> 25 </giorno>
      <mese> 05 </mese>
      <anno> 2022 </anno>
    </data>
    <puntata>
      <minima> 1 </minima>
      <massima> 9999 </massima>
    </puntata>
    <risultato>
      <puntiSquadraCasa>1</puntiSquadraCasa>
      <puntiSquadraTrasferta>2</puntiSquadraTrasferta>
    </risultato>
  </scommessa>
  <scommessa eliminato="0">
    <id> 4 </id>
    <nome>
      <squadraCasa> Milan </squadraCasa>
      <squadraTrasferta> Inter </squadraTrasferta>
    </nome>
    <quotaCalcio>
      <quota1> 1.25 </quota1>
      <quotax> 3.79 </quotax>
      <quota2> 2.79 </quota2>
      <quotaUnder> 1.68 </quotaUnder>
      <quotaOver> 1.24 </quotaOver>
      <quotaGG> 1.85 </quotaGG>
      <quotaNG> 1.35 </quotaNG>
    </quotaCalcio>
    <ora>
      <oraInizio> 20:00 </oraInizio>
      <oraFine> 21:35 </oraFine>
    </ora>
    <data>
      <giorno> 02 </giorno>
      <mese> 07 </mese>
      <anno> 2023 </anno>
    </data>
    <puntata>
      <minima> 1 </minima>
      <massima> 9999 </massima>
    </puntata>
    <risultato>
      <puntiSquadraCasa></puntiSquadraCasa>
      <puntiSquadraTrasferta></puntiSquadraTrasferta>
    </risultato>
  </scommessa>
    <scommessa eliminato="0">
    <id> 5 </id>
    <nome>
      <squadraCasa> Juventus </squadraCasa>
      <squadraTrasferta> Napoli </squadraTrasferta>
    </nome>
    <quotaCalcio>
      <quota1> 2.25 </quota1>
      <quotax> 1.79 </quotax>
      <quota2> 3.79 </quota2>
      <quotaUnder> 2.68 </quotaUnder>
      <quotaOver> 3.24 </quotaOver>
      <quotaGG> 2.85 </quotaGG>
      <quotaNG> 1.35 </quotaNG>
    </quotaCalcio>
    <ora>
      <oraInizio> 20:00 </oraInizio>
      <oraFine> 21:35 </oraFine>
    </ora>
    <data>
      <giorno> 20 </giorno>
      <mese> 07 </mese>
      <anno> 2023 </anno>
    </data>
    <puntata>
      <minima> 1 </minima>
      <massima> 9999 </massima>
    </puntata>
    <risultato>
      <puntiSquadraCasa></puntiSquadraCasa>
      <puntiSquadraTrasferta></puntiSquadraTrasferta>
    </risultato>
  </scommessa>
</calcio>
