=== Sbord1/eldoubleubet/chat.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT chat (message*)>

<!ELEMENT message (id, sender, receiver, text, data, ora)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT sender (#PCDATA)>
<!ELEMENT receiver (#PCDATA)>
<!ELEMENT text (#PCDATA)>

<!ELEMENT data (giorno, mese, anno)>

<!ELEMENT giorno (#PCDATA)>

<!ELEMENT mese (#PCDATA)>

<!ELEMENT anno (#PCDATA)>

<!ELEMENT ora (#PCDATA)>

=== Sbord1/eldoubleubet/chat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chat SYSTEM "chat.dtd">

<chat>

    <message>
        <sender>Alice</sender>
        <receiver>Bob</receiver>
        <text>Hello!</text>
    </message>

    <message>
        <sender>Bob</sender>
        <receiver>Alice</receiver>
        <text>Hi Alice!</text>
    </message>

</chat>
