=== Sbord1/eldoubleubet/forum.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT forum (message*)>

<!ELEMENT message (sender, text, data, ora)>

<!ATTLIST message
            category (calcio | tennis | basket | ippica) #REQUIRED>

<!ELEMENT sender (#PCDATA)>

<!ELEMENT text (#PCDATA)>

<!ELEMENT data (giorno, mese, anno)>

<!ELEMENT giorno (#PCDATA)>

<!ELEMENT mese (#PCDATA)>

<!ELEMENT anno (#PCDATA)>

<!ELEMENT ora (#PCDATA)>

=== Sbord1/eldoubleubet/codice/fileXML/forum/forum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE forum SYSTEM "forum.dtd">
<forum>

    <message category="calcio">
        <sender>ciruzzo</sender>
        <text>Belle partite di calcio</text>
        <data>2023-03-11</data>
        <ora>19:00</ora>
    </message>

    <message category="calcio">
        <sender>mario</sender>
        <text>Sto perdendo tutte le scommesse sul calcio...</text>
        <data>2023-03-12</data>
        <ora>10:00</ora>
    </message>

    <message category="calcio">
        <sender>ciruzzo</sender>
        <text>Non mollare mario!!!</text>
        <data>2023-03-12</data>
        <ora>10:22</ora>
    </message>

    <message category="tennis">
        <sender>mario</sender>
        <text>Quando la prossima partita di Nadal?</text>
        <data>2023-03-12</data>
        <ora>19:05</ora>
    </message>

    <message category="basket">
        <sender>mario</sender>
        <text>Dove posso vedere le partite di basket?</text>
        <data>2023-03-12</data>
        <ora>19:05</ora>
    </message>

    <message category="ippica">
        <sender>mario</sender>
        <text>Dove si trova l'ippodromo a Roma??</text>
        <data>2023-03-12</data>
        <ora>19:05</ora>
    </message>

</forum>
