=== Sbord1/eldoubleubet/proposteScommessaIppica.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT proposteScommessaIppica (propostaScommessa*)>

<!ELEMENT propostaScommessa (id, data, ora, cavalli, distanza, puntata, utente)>

<!ELEMENT data (giorno, mese, anno)>

<!ELEMENT ora (oraInizio, oraFine)>

<!ELEMENT cavalli (cavallo*)>

<!ELEMENT cavallo (nome, numero, quote)>

<!ELEMENT quote (quota1, quota2, quota3)>

<!ELEMENT puntata (minima, massima)>

<!ELEMENT risultato (primo, secondo, terzo)>

<!ELEMENT id (#PCDATA)>

<!ELEMENT giorno (#PCDATA)>

<!ELEMENT mese (#PCDATA)>

<!ELEMENT anno (#PCDATA)>

<!ELEMENT oraInizio (#PCDATA)>

<!ELEMENT oraFine (#PCDATA)>

<!ELEMENT nome (#PCDATA)>

<!ELEMENT numero (#PCDATA)>

<!ELEMENT quota1 (#PCDATA)>

<!ELEMENT quota2 (#PCDATA)>

<!ELEMENT quota3 (#PCDATA)>

<!ELEMENT distanza (#PCDATA)>

<!ELEMENT minima (#PCDATA)>

<!ELEMENT massima (#PCDATA)>

<!ELEMENT primo (#PCDATA)>

<!ELEMENT secondo (#PCDATA)>

<!ELEMENT terzo (#PCDATA)>

<!ELEMENT utente (#PCDATA)>

=== Sbord1/eldoubleubet/proposteScommessaIppica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proposteScommessaIppica SYSTEM "proposteScommessaIppica.dtd">

<proposteScommessaIppica>

    <propostaScommessa>

        <id>1</id>

        <data>
            <giorno>11</giorno>
            <mese>03</mese>
            <anno>2023</anno>
        </data>

        <ora>
            <oraInizio>19:00</oraInizio>
            <oraFine>19:05</oraFine>
        </ora>

        <cavalli>
            <cavallo>
                <nome>Ulysses</nome>
                <numero>1</numero>
                <quote>
                    <quota1>51</quota1>
                    <quota2>21.3</quota2>
                    <quota3>11.2</quota3>
                </quote>
            </cavallo>
            <cavallo>
                <nome>Gun Runner</nome>
                <numero>2</numero>
                <quote>
                    <quota1>71</quota1>
                    <quota2>31.3</quota2>
                    <quota3>11.2</quota3>
                </quote>
            </cavallo>
            <cavallo>
                <nome>Gentildonna</nome>
                <numero>3</numero>
                <quote>
                    <quota1>41</quota1>
                    <quota2>21.3</quota2>
                    <quota3>9.2</quota3>
                </quote>
            </cavallo>
            <cavallo>
                <nome>Orfevre</nome>
                <numero>4</numero>
                <quote>
                    <quota1>51</quota1>
                    <quota2>31.3</quota2>
                    <quota3>8.2</quota3>
                </quote>
            </cavallo>
            <cavallo>
                <nome>HighlandReel</nome>
                <numero>5</numero>
                <quote>
                    <quota1>61</quota1>
                    <quota2>41.3</quota2>
                    <quota3>10.2</quota3>
                </quote>
            </cavallo>
            <cavallo>
                <nome>CapeBlanco</nome>
                <numero>6</numero>
                <quote>
                    <quota1>31</quota1>
                    <quota2>33.3</quota2>
                    <quota3>11.2</quota3>
                </quote>
            </cavallo>
            <cavallo>
                <nome>Montjeu</nome>
                <numero>7</numero>
                <quote>
                    <quota1>61</quota1>
                    <quota2>36.3</quota2>
                    <quota3>11.2</quota3>
                </quote>
            </cavallo>
            <cavallo>
                <nome>Justify</nome>
                <numero>8</numero>
                <quote>
                    <quota1>41</quota1>
                    <quota2>37.3</quota2>
                    <quota3>11.2</quota3>
                </quote>
            </cavallo>
        </cavalli>

        <distanza>1000</distanza>

        <puntata>
			<minima>1</minima>
			<massima>9999</massima>
		</puntata>

        <utente>tuzzo18</utente>

    </propostaScommessa>

</proposteScommessaIppica>
