=== Sbord1/eldoubleubet/richiesteAccredito.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT richiesteAccredito (richiesta*)>

<!ELEMENT richiesta (id, richiedente, somma)>

<!ATTLIST richiesta
            status (in-sospeso | accettata | rifiutata) "in-sospeso">

<!ELEMENT id (#PCDATA)>

<!ELEMENT richiedente (#PCDATA)>

<!ELEMENT somma (#PCDATA)>

=== Sbord1/eldoubleubet/richiesteAccredito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE richiesteAccredito SYSTEM "richiesteAccredito.dtd">

<richiesteAccredito>

    <richiesta status="in-sospeso">
        <id>1</id>
        <!-- username dell'utente scommettitore che ha richiesto l'accredito -->
        <richiedente>matteo</richiedente>
        <!-- quantita' di credito richiesta -->
        <somma>50</somma>
    </richiesta>

    <richiesta status="accettata">
        <id>2</id>
        <richiedente>matteo</richiedente>
        <somma>100</somma>
    </richiesta>

    <richiesta status="rifiutata">
        <id>3</id>
        <richiedente>matteo</richiedente>
        <somma>20</somma>
    </richiesta>

</richiesteAccredito>

=== Sbord1/eldoubleubet/codice/fileXML/richiesteAccredito/richiesteAccredito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE richiesteAccredito SYSTEM "richiesteAccredito.dtd">

<richiesteAccredito>

    <richiesta status="in-sospeso">
        <id>1</id>
        <richiedente>mario</richiedente>
        <somma>50</somma>
    </richiesta>

    <richiesta status="accettata">
        <id>2</id>
        <richiedente>ciruzzo</richiedente>
        <somma>100</somma>
    </richiesta>

    <richiesta status="rifiutata">
        <id>3</id>
        <richiedente>mario</richiedente>
        <somma>20</somma>
    </richiesta>

</richiesteAccredito>
