=== Sbord1/eldoubleubet/scommesseCalcio.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Definisco le scommesse relative al calcio di un utente -->
<!ELEMENT scommesseCalcio (scommessa*)>
<!ELEMENT scommessa (id, scommettitore, risultato, puntata)>

<!ATTLIST scommessa
              eliminato ("1" | "0") "0" #REQUIRED> 

<!ELEMENT id (#PCDATA)>

<!ELEMENT scommettitore (#PCDATA)>

<-- elemento esito composto da "1","x","2" oppure vuoto, elemento goal composto da "si", "no" oppure vuoto, elemento under composto da "si", "no", oppure vuoto -->
<!ELEMENT risultato (esito, goal, under)>
<!ELEMENT esito (#PCDATA)>
<!ELEMENT goal (#PCDATA)>
<!ELEMENT under (#PCDATA)>

<!ELEMENT puntata (#PCDATA)>

=== Sbord1/eldoubleubet/codice/fileXML/scommesseUtenti/scommesseCalcio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scommesseCalcio SYSTEM "scommesseCalcio.dtd">
<!-- Esempi di 3 scommesse di calcio -->
<!-- L'id della scommessa equivale all'id della partita cui si riferisce la scommessa -->
<scommesseCalcio>
  <!-- utente mario ha puntato 30 crediti sulla vittoria della squadra in casa -->
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>mario</scommettitore>
        <risultato>1</risultato>
        <puntata>30</puntata>
    </scommessa>
     <!-- utente ciruzzo ha puntato 18 crediti su "Goal" (segnano entrambe le squadre) -->
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>ciruzzo</scommettitore>
        <risultato>GG</risultato>
        <puntata>18</puntata>
    </scommessa>
   <!-- utente mario ha puntato 10 crediti su "Over 2.5" (piu' di 2 goal) -->
    <scommessa eliminato="0">
        <id>2</id>
        <scommettitore>mario</scommettitore>
        <risultato>Over</risultato>
        <puntata>10</puntata>
    </scommessa>
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>ciruzzo</scommettitore>
        <risultato>NG</risultato>
        <puntata>5</puntata>
    </scommessa>
    <scommessa eliminato="0">
        <id>1</id>
        <scommettitore>mario</scommettitore>
        <risultato>2</risultato>
        <puntata>30</puntata>
    </scommessa>
    <scommessa eliminato="0">
        <id>2</id>
        <scommettitore>mario</scommettitore>
        <risultato>Under</risultato>
        <puntata>10</puntata>
    </scommessa>
</scommesseCalcio>
